version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      ansible:
        patterns: ['*']
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: monthly
  - package-ecosystem: terraform
    directory: /terraform/object-storage
    schedule:
      interval: monthly
